# Generated by Django 2.1.1 on 2022-01-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogging", "0003_auto_20211222_1118"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="posts",
        ),
        migrations.AddField(
            model_name="category",
            name="posts",
            field=models.ManyToManyField(
                blank=True, related_name="categories", to="blogging.Post"
            ),
        ),
    ]
